In [9]:
import torch
import pandas as pd
import numpy as np

In [10]:
train_df = pd.read_csv("data/internal/splits/final/train.csv")
attr = train_df.columns[1:19]

In [11]:
counts = train_df[attr].sum(axis=0)  # occurence counts
dict(counts)

{'p_camera_reaction': 1561,
 'p_tool_use': 807,
 'p_object_carrying': 458,
 'p_bipedal': 97,
 'p_feeding': 4412,
 'p_chimp_carrying': 1332,
 'p_vocalisation': 722,
 'p_climbing': 1430,
 'p_aggression': 122,
 'p_travel': 3655,
 'p_sex': 116,
 'p_piloerection': 33,
 'p_social_interaction': 1359,
 'p_grooming': 455,
 'p_display': 160,
 'p_cross_species_interaction': 81,
 'p_resting': 3013,
 'p_no_behaviour': 3091}

In [14]:
label_freq = dict(counts)
label_freq = dict(sorted(label_freq.items()))
label_freq_array = np.array(list(label_freq.values()))
label_freq_array = label_freq_array / label_freq_array.sum()
adjustments = np.log(label_freq_array**1.0 + 1e-12)
adjustments = torch.from_numpy(adjustments)

In [19]:
torch.nn.functional.softmax(adjustments)

<ipython-input-19-28533b02d8e4>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.softmax(adjustments)


tensor([0.0053, 0.0042, 0.0682, 0.0582, 0.0624, 0.0035, 0.0070, 0.1926, 0.0199,
        0.1350, 0.0200, 0.0014, 0.1315, 0.0051, 0.0593, 0.0352, 0.1596, 0.0315],
       dtype=torch.float64)

In [20]:
adjustments

tensor([-5.2350, -5.4644, -2.6860, -2.8446, -2.7736, -5.6446, -4.9639, -1.6470,
        -3.9188, -2.0028, -3.9122, -6.5426, -2.0284, -5.2855, -2.8246, -3.3457,
        -1.8352, -3.4570], dtype=torch.float64)

In [21]:
x = torch.tensor(
    [
        -5.2350,
        -5.4644,
        -2.6860,
        -2.8446,
        -2.7736,
        -5.6446,
        -4.9639,
        -1.6470,
        -3.9188,
        -2.0028,
        -3.9122,
        -6.5426,
        -2.0284,
        -5.2855,
        -2.8246,
        -3.3457,
        -1.8352,
        -3.4570,
    ],
    dtype=torch.float32,
)

In [22]:
x

tensor([-5.2350, -5.4644, -2.6860, -2.8446, -2.7736, -5.6446, -4.9639, -1.6470,
        -3.9188, -2.0028, -3.9122, -6.5426, -2.0284, -5.2855, -2.8246, -3.3457,
        -1.8352, -3.4570])